### ISSUE TITLE
default 'user-agent' header sends requests as a browser

### ISSUE THREAD

**Issue by ericavonb** [Clever/quest#21]
Set the default 'user-agent' header on requests to versioned Node.js and quest lib. The default is currently 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3) AppleWebKit/537.16 (KHTML, like Gecko) Chrome/24.0.1297.0 Safari/537.16'. This tells the responding server that the request is coming from a browser. As most use-cases for this library are on the Node.js backend, this is more often than not the incorrect user-agent.

Some servers treat requests from browsers differently because they need to do work-arounds for some issues (i.e. same-origin restrictions). For example, as a way to get data from a POST after a user to redirected to a URL, some servers return HTML that automatically submits a POST form for GET requests from browsers. This means requests to these URLs will not return the expected data.

**Comment by azylman** [comment]
Given how differently servers treat requests from browser v not-browser, this might need to be a breaking change

**Comment by ericavonb** [comment]
Could we make it an option, like `browser: true` where true is the default?

**Comment by azylman** [comment]
What's the benefit of that? It wouldn't change the default behavior OR the behavior if you override the `user-agent`, right? Seems confusing to me.
